name_map = {
    'Alex De Minaur': 'De Minaur A.',
    'Alejandro Davidovich Fokina': 'Davidovich Fokina A.',
    'Zhizhen Zhang': 'Zhang Z.',
    'Roberto Bautista Agut': 'Bautista Agut R.',
    'Botic Van De Zandschulp': 'Van De Zandschulp B.',
    'Christopher Oconnell': 'Oconnell C.',
    'Roberto Carballes Baena': 'Carballes Baena R.',
    'Luca Van Assche': 'Van Assche L.',
    'Tomas Martin Etcheverry': 'Martin Etcheverry T.',
    'Jesper De Jong': 'De Jong J.',
    'Felix Auger Aliassime': 'Auger Aliassime F.',
    'Pablo Llamas Ruiz': 'Llamas Ruiz P.',
    'Facundo Diaz Acosta': 'Diaz Acosta F.',
    'Bernabe Zapata Miralles': 'Zapata Miralles B.',
    'Albert Ramos': 'Ramos A.',
    'Roman Andres Burruchaga': 'Burruchaga R.',
    'Nicolas Moreno De Alboran': 'Moreno De Alboran N.',
    'Camilo Ugo Carabelli': 'Ugo Carabelli C.',
    'Thiago Seyboth Wild': 'Seyboth Wild T.',
    'Felipe Meligeni Alves': 'Meligeni Alves F.',
    'Tomas Barrios Vera': 'Barrios Vera T.',
    'David Jorda Sanchis': 'Jorda Sanchis D.',
    'Alejandro Moro Canas': 'Moro Canas A.',
    'Giovanni Mpetshi Perricard': 'Mpetshi Perricard G.',
    'Vasek Pospisil': 'Pospisil V.',
    'Ignacio Buse': 'Buse I.',
    'Vit Kopriva': 'Kopriva V.',
    'Zsombor Piros': 'Piros Z.',
    'Alex Molcan': 'Molcan A.',
    'Lukas Pokorny': 'Pokorny L.',
    'Elias Ymer': 'Ymer E.',
    'Nerman Fatic': 'Fatic N.',
    'Damir Dzumhur': 'Dzumhur D.',
    'Petr Nesterov': 'Nesterov P.',
    'Chris Rodesch': 'Rodesch C.',
    'Alex Knaff': 'Knaff A.',
    'Nicolas Mejia': 'Mejia N.',
    'Adria Soriano Barrera': 'Soriano Barrera A.',
    'Mohamed Safwat': 'Safwat M.',
    'Amr Elsayed Abdou Ahmed Mohamed': 'Mohamed A.',
    'Andres Andrade': 'Andrade A.',
    'Aristotelis Thanos': 'Thanos A.',
    'Ioannis Xilas': 'Xilas I.',
    'Lucas Miedler': 'Miedler L.',
    'Benjamin Hassan': 'Hassan B.',
    'Saba Purtseladze': 'Purtseladze S.',
    'Ricardas Berankis': 'Berankis R.',
    'Vilius Gaubas': 'Gaubas V.',
    'Elmer Moller': 'Moller E.',
    'Rodrigo Pacheco Mendez': 'Pacheco Mendez R.',
    'August Holmgren': 'Holmgren A.',
    'Viktor Durasovic': 'Durasovic V.',
    'Nicolai Budkov Kjaer': 'Budkov Kjaer N.',
    'Kiranpal Pannu': 'Pannu K.',
    'Yanki Erel': 'Erel Y.',
    'Altug Celikbilek': 'Celikbilek A.',
    'Ramkumar Ramanathan': 'Ramanathan R.',
    'N Sriram Balaji': 'Sriram Balaji N.',
    'Niki Kaliyanda Poonacha': 'Kaliyanda Poonacha N.',
    'Maks Kasnikowski': 'Kasnikowski M.',
    'Kamil Majchrzak': 'Majchrzak K.',
    'Juan Carlos Prado Angelo': 'Prado Angelo J.',
    'Murkel Alejandro Dellien Velasco': 'Dellien Velasco M.',
    'Boris Arias': 'Arias B.',
    'Sebastian Dominko': 'Dominko S.',
    'Yassine Dlimi': 'Dlimi Y.',
    'Elliot Benchetrit': 'Benchetrit E.',
    'Stylianos Christodoulou': 'Christodoulou S.',
    'Diego Duran': 'Duran D.',
    'Marcelo Arevalo': 'Arevalo M.',
    'Juan Carlos Fuentes Vasquez': 'Fuentes Vasquez J.',
    'Hong Kit Jack Wong': 'Wong H.',
    'Benedict Badza': 'Badza B.',
    'Blaise Bicknell': 'Bicknell B.',
    'Darian King': 'King D.',
    'Kaipo Marshall': 'Marshall K.',
    'Daniel Vallejo': 'Vallejo D.',
    'Valentin Vacherot': 'Vacherot V.',
    'Fitriadi M Rifqi': 'Rifqi F.M.',
    'Thomas Yaka Kofi Setodji': 'Setodji T.Y.K.',
    'Komlavi Loglo': 'Loglo K.',
    'Moez Echargui': 'Echargui M.',
    'Aziz Dougaz': 'Dougaz A.',
    'Franco Roncadelli': 'Roncadelli F.',
    'Joaquin Aguilar Cardozo': 'Aguilar Cardozo J.',
    'Nam Hoang Ly': 'Ly N.H.',
    'Kris Van Wyk': 'Van Wyk K.',
    'Philip Henning': 'Henning P.'
}